### ISSUE TITLE
Missing members in the typechain

### ISSUE THREAD

**Issue by kaiserfr** [alpaca-finance/bsc-alpaca-contract#131]
I have difficulties running the tests.
- I installed node artefacts using npm install
- I provided one arbitrary privateKey in hardhat.config.ts:22
- I ran npx hardhat test

This resulted in the errors below:

test/CakeMaxiWorker.test.ts:9:3 - error TS2724: '"../typechain"' has no exported member named 'PancakeFactory'. Did you mean 'IPancakeFactory'?
test/CakeMaxiWorker.test.ts:10:3 - error TS2724: '"../typechain"' has no exported member named 'PancakeFactoryfactory'. Did you mean 'IPancakeFactoryfactory'?

Are there classes missing or did I do somenthing wrong?
Can anyone publish how to setup this project in order to run the tests?

**Comment by spicysquid168** [comment]
You will need to run `yarn compile` to get all contracts compiled and build `typechain` first before running the tests.

**Comment by hoinamIddy** [comment]
When I try to deploy, I got an error saying they cannot find the json files inside /deploy/results. How do I get those json files?
