### ISSUE TITLE
does alpaca accept new liquidation bot whitelist applications?

### ISSUE THREAD

**Issue by liusDong** [alpaca-finance/bsc-alpaca-contract#227]
As a user who has been using the alpaca finance for one year, I want to make my own contribution to the protocol by becoming a liquidation robot. Now that you have entered a new chain, can you accept the application for a new liquidation robot?

**Comment by alpanaca** [comment]
Hi @liusDong.

For liquidation bot application, please send the email to request@alpacafinance.org.
