### ISSUE TITLE
Update documentation links to contracts

### ISSUE THREAD

**Issue by nicotrozzo** [alpaca-finance/bsc-alpaca-contract#283]
I saw you changed your directory structure for your contracts, and checking the [Contracts Documentation](https://alpaca-doc.s3.ap-southeast-1.amazonaws.com/lyf/Export-849cfdb0-24b6-4655-a19b-1734b8a1c2b3/Contract%20Documentation%204c48a0c0db7442c6aa0268dd110e6b80/Vault%20Contract%20bfb2f32d0e444ffdadcc348f2c3b5384.html) I noticed your links aren't updated. 
Probably not your biggest priority right now, just to let you know.

**Comment by alpanaca** [comment]
Hi @nicotrozzo,

Thanks for reaching out. We'll update it once we're settled with the new structure.

**Comment by alpanaca** [comment]
Done
