### ISSUE TITLE
pdf compilation problem in Certik audit report?

### ISSUE THREAD

**Issue by Qumeric** [alpaca-finance/bsc-alpaca-contract#38]
https://github.com/alpaca-finance/bsc-alpaca-contract/blob/main/audits/CertiK%20Security%20Assessment%20for%20Alpaca%20Finance.pdf

Most pages are incomplete, i.e. last part of page is cutted on seemingly random moment. A lot of sentences are cutted in the middle. 

I am pretty sure that it is result of improper pdf compilation, probably recompiling source would fix this issue.

**Comment by ricardo-alpaca** [comment]
I downloaded the pdf file into my computer and it displayed correctly. My guess is it is the rendering problem with GitHub itself. Could you try downloading and viewing the pdf on your computer?
